import os
from pathlib import Path
from typing import List

from src.llm.llm_client import generate_completion

# Directory where current game rule documents are stored
RULES_DIR = Path(__file__).parent.parent / "design"


def load_rule_files(
    rules_dir: Path = RULES_DIR,
    extensions: List[str] = [".md", ".txt"]
) -> List[str]:
    """
    Load text content from rule definition files in the design directory.

    Args:
        rules_dir: Path to the directory containing rule docs.
        extensions: File extensions to include.

    Returns:
        A list of file contents as strings.
    """
    contents = []
    for path in rules_dir.rglob("*"):
        if path.suffix.lower() in extensions:
            try:
                contents.append(path.read_text(encoding="utf-8"))
            except Exception:
                # Skip unreadable files
                continue
    return contents


def compact_rules(
    rule_texts: List[str],
    max_chars: int = 5000
) -> str:
    """
    Combine and truncate rule texts to fit within a character limit.

    Args:
        rule_texts: List of rule document contents.
        max_chars: Maximum characters for the combined rules summary.

    Returns:
        A single string containing the (possibly truncated) combined rules.
    """
    combined = "\n\n".join(rule_texts)
    if len(combined) > max_chars:
        return combined[:max_chars] + "\n\n[...truncated]"
    return combined


def create_initial_prompt(
    initial_details: str,
    rules_dir: Path = RULES_DIR
) -> str:
    """
    Construct the initial prompt for the Game Master LLM on game creation.

    Args:
        initial_details: Human GM's setup instructions for the new game.
        rules_dir: Directory containing rule docs.

    Returns:
        A prompt string including rules and setup details.
    """
    # Load and compact current rule definitions
    rule_texts = load_rule_files(rules_dir)
    rules_summary = compact_rules(rule_texts)

    prompt = (
        "You are the Game Master AI for the Influence RPG.\n"
        "Below is the current game rule set (subject to updates during development):\n\n"
        f"{rules_summary}\n\n"
        "The human GM has provided these setup details for this new game:\n\n"
        f"{initial_details}\n\n"
        "Based on the rules and the setup, generate an initial narrative scene to start the adventure."
    )
    
    # LOG IT:
    #print("=== INITIAL GM PROMPT ===")
    #print(prompt)
    #print("=========================")
    return prompt


def generate_initial_scene(initial_details: str) -> str:
    """
    Generate the first narrative scene by calling the LLM with the constructed prompt.

    Args:
        initial_details: Human GM's setup instructions.

    Returns:
        The narrative scene generated by the LLM.
    """
    prompt = create_initial_prompt(initial_details)
    return generate_completion(prompt)
